name: Update Version on Release

on:
  release:
    types:
      - created

jobs:
  update_version:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with: 
          command: yarn all:aboard
          
